const DropDownSelectList = {
    Types: [
        { value: "", label: "Select Type" },
        { value: "Arm Band Case", label: "Arm Band Case" },
        { value: "Back Cover", label: "Back Cover" },
        { value: "Back Replacement Cover", label: "Back Replacement Cover" },
        { value: "Book Cover", label: "Book Cover" },
        { value: "Bumper Case", label: "Bumper Case" },
        { value: "Flip Cover", label: "Flip Cover" },
        { value: "Front & Back Case", label: "Front & Back Case" },
        { value: "Keyboard Case", label: "Keyboard Case" },
        { value: "Memory Card Case", label: "Memory Card Case" },
        { value: "Pouch", label: "Pouch" },
        { value: "Sleeve", label: "Sleeve" },
        { value: "Speaker Case Cover", label: "Speaker Case Cover" },
        { value: "Wallet Case Cover", label: "Wallet Case Cover" }
    ],
    Themes: [
        { value: "", label: "Select Theme" },
        { value: "3D/Hologram", label: "3D/Hologram" },
        { value: "Animals/Birds/Nature", label: "Animals/Birds/Nature" },
        { value: "Automobiles", label: "Automobiles" },
        { value: "Comics/Cartoons/Superheroes", label: "Comics/Cartoons/Superheroes" },
        { value: "Famous Personalities", label: "Famous Personalities" },
        { value: "For Her", label: "For Her" },
        { value: "Geeky/Mathematical", label: "Geeky/Mathematical" },
        { value: "Glitter", label: "Glitter" },
        { value: "LED Case", label: "LED Case" },
        { value: "Marble", label: "Marble" },
        { value: "Movies/Music/TV Series", label: "Movies/Music/TV Series" },
        { value: "No Theme", label: "No Theme" },
        { value: "Painting/Drawing/Sketches", label: "Painting/Drawing/Sketches" },
        { value: "Patterns", label: "Patterns" },
        { value: "Quotes/Signs/Symbols", label: "Quotes/Signs/Symbols" },
        { value: "Religion/Festivals/Spiritual", label: "Religion/Festivals/Spiritual" },
        { value: "See-through Design", label: "See-through Design" },
        { value: "Sports & Sportstars", label: "Sports & Sportstars" },
        { value: "Travel/Photography", label: "Travel/Photography" },
        { value: "Vintage & History", label: "Vintage & History" },
        { value: "Wooden", label: "Wooden" }
    ],
    Materials: [
        { value: "", label: "Select Material" },
        { value: "Aramid Fiber", label: "Aramid Fiber" },
        { value: "Artificial Leather", label: "Artificial Leather" },
        { value: "Cloth", label: "Cloth" },
        { value: "Fiber", label: "Fiber" },
        { value: "Glass", label: "Glass" },
        { value: "Leather", label: "Leather" },
        { value: "Metal", label: "Metal" },
        { value: "Plastic", label: "Plastic" },
        { value: "Polycarbonate", label: "Polycarbonate" },
        { value: "Rubber", label: "Rubber" },
        { value: "Silicon", label: "Silicon" },
        { value: "Thermoplastic Polyurethane", label: "Thermoplastic Polyurethane" },
        { value: "Wood", label: "Wood" }
    ],
    Colors: [
        { value: "", label: "Select Color" },
        { value: "Beige", label: "Beige" },
        { value: "Black", label: "Black" },
        { value: "Blue", label: "Blue" },
        { value: "Brown", label: "Brown" },
        { value: "Gold", label: "Gold" },
        { value: "Green", label: "Green" },
        { value: "Grey", label: "Grey" },
        { value: "Khaki", label: "Khaki" },
        { value: "Maroon", label: "Maroon" },
        { value: "Multicolor", label: "Multicolor" },
        { value: "Orange", label: "Orange" },
        { value: "Pink", label: "Pink" },
        { value: "Purple", label: "Purple" },
        { value: "Red", label: "Red" },
        { value: "Silver", label: "Silver" },
        { value: "Transparent", label: "Transparent" },
        { value: "White", label: "White" },
        { value: "Yellow", label: "Yellow" }
    ],
    BrandColors: [
        { value: "", label: "Select Brand Color" },
        { value: "Beige", label: "Beige" },
        { value: "Black", label: "Black" },
        { value: "Blue", label: "Blue" },
        { value: "Brown", label: "Brown" },
        { value: "Gold", label: "Gold" },
        { value: "Green", label: "Green" },
        { value: "Grey", label: "Grey" },
        { value: "Khaki", label: "Khaki" },
        { value: "Maroon", label: "Maroon" },
        { value: "Multicolor", label: "Multicolor" },
        { value: "Orange", label: "Orange" },
        { value: "Pink", label: "Pink" },
        { value: "Purple", label: "Purple" },
        { value: "Red", label: "Red" },
        { value: "Silver", label: "Silver" },
        { value: "Transparent", label: "Transparent" },
        { value: "White", label: "White" },
        { value: "Yellow", label: "Yellow" }
    ],
    Devices: [
        { value: "", label: "Select Suitable Device" },
        { value: "Audio Player", label: "Audio Player" },
        { value: "Bluetooth Speaker", label: "Bluetooth Speaker" },
        { value: "Gaming Console", label: "Gaming Console" },
        { value: "Hard Drive", label: "Hard Drive" },
        { value: "Laptop", label: "Laptop" },
        { value: "Memory Card", label: "Memory Card" },
        { value: "Mobile", label: "Mobile" },
        { value: "Smartwatch", label: "Smartwatch" },
        { value: "Tablet", label: "Tablet" },
        { value: "WiFi Hotspot", label: "WiFi Hotspot" },
        { value: "iPod", label: "iPod" }
    ],
    Features: [
        { value: "", label: "Select Features" },
        { value: "3D Case", label: "3D Case" },
        { value: "Anti-radiation", label: "Anti-radiation" },
        { value: "Band", label: "Band" },
        { value: "Bezel Stand", label: "Bezel Stand" },
        { value: "Bluetooth Shutter", label: "Bluetooth Shutter" },
        { value: "Cable Organiser", label: "Cable Organiser" },
        { value: "Camera Bump Protector", label: "Camera Bump Protector" },
        { value: "Cases with Holder", label: "Cases with Holder" },
        { value: "Charging Case", label: "Charging Case" },
        { value: "Dot View", label: "Dot View" },
        { value: "Dual Protection", label: "Dual Protection" },
        { value: "Flexible", label: "Flexible" },
        { value: "Grip Case", label: "Grip Case" },
        { value: "Hard Case", label: "Hard Case" },
        { value: "Holster", label: "Holster" },
        { value: "Hybrid TPU", label: "Hybrid TPU" },
        { value: "Indian TPU", label: "Indian TPU" },
        { value: "Laptop Case", label: "Laptop Case" },
        { value: "Magnetic Case", label: "Magnetic Case" },
        { value: "Matte Finish", label: "Matte Finish" },
        { value: "Ribbon Case", label: "Ribbon Case" },
        { value: "Ring Case", label: "Ring Case" },
        { value: "Rugged Armor", label: "Rugged Armor" },
        { value: "Shock Proof", label: "Shock Proof" },
        { value: "Sound Amplifying Case", label: "Sound Amplifying Case" },
        { value: "Three in One", label: "Three in One" },
        { value: "Waterproof", label: "Waterproof" },
        { value: "None", label: "None" }
    ],
    InsidePacks: [
        { value: "", label: "Select Features" },
        { value: "Arm Band Case", label: "Arm Band Case" },
        { value: "Back Cover", label: "Back Cover" },
        { value: "Back Replacement Cover", label: "Back Replacement Cover" },
        { value: "Book Cover", label: "Book Cover" },
        { value: "Bumper Case", label: "Bumper Case" },
        { value: "Flip Cover", label: "Flip Cover" },
        { value: "Front & Back Case", label: "Front & Back Case" },
        { value: "Keyboard Case", label: "Keyboard Case" },
        { value: "Memory Card Case", label: "Memory Card Case" },
        { value: "Pouch", label: "Pouch" },
        { value: "Sleeve", label: "Sleeve" },
        { value: "Speaker Case Cover", label: "Speaker Case Cover" },
        { value: "Wallet Case Cover", label: "Wallet Case Cover" }
    ]
};

export default DropDownSelectList